android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
android.enableD8Desugaring=false
org.gradle.jvmargs=-Xmx4g
android.suppressUnsupportedCompileSdk=34
android.ndk.suppressMinSdkVersionError=21








