// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'e4129586268d9c5246c56ecc516b71fb01c7f8f3',
  //   appId: '1:239990980735:android:1a675ca93c511c76ef7f4a',
  //   messagingSenderId: '115177822747850106759',
  //   projectId: 'astroway-diply',
  //   storageBucket: 'astroway-diply.appspot.com',
  // );


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD65BBoYaEou8rLMWyF2dYQQ88_ioZa3VY',
    appId: '1:44565728556:android:88e82ec3ba5eff54cd7089',
    messagingSenderId: '44565728556', // extracted from appId
    projectId: 'jyotishiastro-fbd16',
    storageBucket: 'jyotishiastro-fbd16.firebasestorage.app',
  );


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNWnN2vKDFSOeTwa1L5yiFxaYsxt',
    appId: '1:381086206621:android:4bdb41c9c0716b32e274',
    messagingSenderId: '3810206621',
    projectId: 'astroway-diply',
    storageBucket: 'astroway-diply.appspot.com',
    iosBundleId: 'com.diply.astrologer',
  );
} //646392
